### ISSUE TITLE
Access tp the API has been BLocked by CORS policy

### ISSUE THREAD

**Issue by abdoolkadir** [sggts04/thanosapi#5]
I tried to use the api for a mini project i'm building and it keeps returning this error: Access to XMLHttpRequest at 'https://thanosapi.herokuapp.com/random/' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

can you please allow request to the API on your Origin. refer to this MSDN doc for more details: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin . thank you.

**Comment by sggts04** [comment]
will look into this

**Comment by iAmLakshya** [comment]
> will look into this

Hey, It's a very simple fix, just install CORS middleware and enable it globally for all routes.

For your reference: https://expressjs.com/en/resources/middleware/cors.html

**Comment by sggts04** [comment]
thanks @iAmLakshya 

@Abu-mus-ab patch is up, if you could test once then I would close this issue.

**Comment by abdoolkadir** [comment]
> thanks @iAmLakshya
> 
> @Abu-mus-ab patch is up, if you could test once then I would close this issue.

yes i just tested it and its working. Thank you very Much! I really appreciate!
